#!/usr/bin/env python3
import numpy as np
from pathlib import Path
from sklearn.decomposition import PCA
import argparse
import sys
import subprocess

# List of all transition metals
TRANSITION_METALS = {
    "Sc","Ti","V","Cr","Mn","Fe","Co","Ni","Cu","Zn",
    "Y","Zr","Nb","Mo","Tc","Ru","Rh","Pd","Ag","Cd",
    "Hf","Ta","W","Re","Os","Ir","Pt","Au","Hg"
}

def read_xyz(filename):
    with open(filename) as f:
        n_atoms = int(f.readline())
        f.readline()  # skip comment line
        atoms = []
        coords = []
        for _ in range(n_atoms):
            line = f.readline().split()
            atoms.append(line[0])
            coords.append([float(x) for x in line[1:4]])
    return atoms, np.array(coords)

def write_xyz(filename, atoms, coords):
    with open(filename, "w") as f:
        f.write(f"{len(atoms)}\nAligned molecule\n")
        for a, (x, y, z) in zip(atoms, coords):
            f.write(f"{a:2} {x: .6f} {y: .6f} {z: .6f}\n")

def find_metal(atoms, specified=None):
    if specified:
        for i, a in enumerate(atoms):
            if a == specified:
                return i
        sys.exit(f"Specified metal '{specified}' not found in XYZ file")
    else:
        for i, a in enumerate(atoms):
            if a in TRANSITION_METALS:
                return i
        sys.exit("No transition metal found in XYZ file")

def align_molecule(xyz_file, metal=None, cutoff=3.0):
    atoms, coords = read_xyz(xyz_file)
    metal_idx = find_metal(atoms, specified=metal)

    # Translate metal to origin
    coords -= coords[metal_idx]

    # Select local coordination sphere (exclude metal itself)
    distances = np.linalg.norm(coords, axis=1)
    local_idxs = [i for i, d in enumerate(distances) if 0.0 < d <= cutoff]
    if not local_idxs:
        print("No atoms found in cutoff; using all atoms for PCA")
        local_idxs = list(range(len(atoms)))

    # PCA rotation
    pca = PCA(n_components=3)
    pca.fit(coords[local_idxs])
    coords_rot = coords @ pca.components_.T

    # write aligned XYZ
    out_file = Path(xyz_file).with_name(Path(xyz_file).stem + "_0.xyz")
    write_xyz(out_file, atoms, coords_rot)
    print(f"Aligned XYZ written to {out_file}")

    return out_file

def main():
    parser = argparse.ArgumentParser(description="Metal-centered PCA alignment for XYZ files")
    parser.add_argument("xyz_file", help="Input XYZ file")
    parser.add_argument("--metal", help="Specify metal atom (optional)", default=None)
    parser.add_argument("--cutoff", type=float, help="Coordination sphere cutoff in Å", default=3.0)
    parser.add_argument("--print", action="store_true", help="Run xyz2tab.py after alignment")
    args = parser.parse_args()

    aligned_file = align_molecule(args.xyz_file, metal=args.metal, cutoff=args.cutoff)

    #output_dir = Path.home() / "qchem" / "xyz" / "md_tables"
    #output_dir.mkdir(exist_ok=True)  # make folder if it doesn’t exist
    #md_file = output_dir / f"{aligned_file.stem}.md"
    md_file = aligned_file.with_suffix(".md")

    if args.print:
        xyz2tab_path = Path.home() / "qchem" / "xyz" / "xyz2tab.py"
        if not xyz2tab_path.exists():
            print(f"xyz2tab.py not found at {xyz2tab_path}") 
            return 
       
        fixed_args = '-sn -so'
        try:
            subprocess.run(f"python3 {xyz2tab_path} {aligned_file} > {md_file} {fixed_args}",shell=True, check=True) 
            print("Markdown table and plot generated by xyz2tab.py")
        except subprocess.CalledProcessError as e: 
            print(f"xyz2tab.py failed: {e}")


if __name__ == "__main__":
    main()
